version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 18...
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
